apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: mcp-operator
  app.kubernetes.io/component: observability

configMapGenerator:
- name: grafana-dashboard
  files:
  - dashboard.json
  options:
    disableNameSuffixHash: true
    labels:
      grafana_dashboard: "1"
    annotations:
      grafana.io/folder: "MCP Operator"
