apiVersion: mcp.mcp-operator.io/v1
kind: MCPServer
metadata:
  name: mcp-basic-example
spec:
  image: "tzolov/mcp-everything-server:v3"
  command: ["node", "dist/index.js", "streamableHttp"]

  # Streamable HTTP transport
  transport:
    type: "http"
    protocol: "streamable-http"
    config:
      http:
        port: 3001  # StreamableHttp server listens on 3001
        path: "/mcp"
        sessionManagement: true
