## Append samples of your project ##
resources:
- wikipedia-http.yaml
- mcp-basic-example.yaml
- mcp-complete-example.yaml
- mcp-sse-example.yaml
- mcp_v1_mcpserver_metrics.yaml
- mcp_v1_mcpserver_metrics_advanced.yaml
- mcp_v1_mcpserver_metrics_sse.yaml
- poddisruptionbudget-example.yaml
- networkpolicy-example.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
