## Append samples of your project ##
resources:
- 01-wikipedia-sse.yaml
- 02-streamable-http-basic.yaml
- 03-sse-optimized.yaml
- 04-metrics-basic.yaml
- 05-metrics-advanced.yaml
- 06-metrics-sse.yaml
- 10-complete-reference.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
